#!/usr/bin/env python3
"""Evaluate native H--EFTCAMB R-Universe f sigma8 predictions from P(k,z).

The input spectra must have been generated by ``generate_heftcamb_rph.py``
for the same KGB action point, including z-dz, z, and z+dz for every RSD
redshift.  sigma8 is integrated directly from the solver's linear total-matter
power spectrum.  f sigma8 is then d sigma8/d ln(a), using a symmetric finite
difference in the independently evolved spectra.

The supplied Sagredo--BOSS compilation is deliberately treated as a residual
audit, not a global RSD likelihood: it contains survey groups without their
cross-covariances or fiducial-cosmology/window-function likelihoods.  The
records explicitly labelled ``diag`` receive a separately labelled diagonal
diagnostic sum only; it is never combined with the Planck--SN--BAO--CC statistic.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
from pathlib import Path
from typing import Any

import numpy as np
from scipy.integrate import simpson


ROOT = Path(__file__).resolve().parents[1]
SIGMA8_PATTERN = re.compile(r"at z =\s*([-+0-9.eE]+) sigma8 \(all matter\) =\s*([-+0-9.eE]+)")
VELOCITY_GROWTH_PATTERN = re.compile(r"at z =\s*([-+0-9.eE]+) sigma8\^2_vd/sigma8\s*=\s*([-+0-9.eE]+)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--solver-dir", type=Path, required=True, help="Completed H--EFTCAMB output directory.")
    parser.add_argument("--rsd-data", type=Path, required=True, help="CSV RSD diagnostic compilation.")
    parser.add_argument("--finite-difference-dz", type=float, default=0.005)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def redshift_tag(redshift: float) -> str:
    return f"z{redshift:.6f}".replace(".", "p")


def matter_power_path(solver_dir: Path, redshift: float) -> Path:
    return solver_dir / f"ru_kgb_rph_matterpower_{redshift_tag(redshift)}.dat"


def top_hat_window(x: np.ndarray) -> np.ndarray:
    result = np.empty_like(x)
    small = np.abs(x) < 1.0e-3
    # W(x)=1-x^2/10+x^4/280+O(x^6) avoids cancellation at small x.
    xs = x[small]
    result[small] = 1.0 - xs * xs / 10.0 + xs**4 / 280.0
    xl = x[~small]
    result[~small] = 3.0 * (np.sin(xl) - xl * np.cos(xl)) / xl**3
    return result


def sigma8_from_linear_power(path: Path) -> float:
    if not path.is_file():
        raise FileNotFoundError(f"missing native matter-power output: {path}")
    table = np.loadtxt(path, comments="#")
    if table.ndim != 2 or table.shape[1] < 2:
        raise RuntimeError(f"expected two-column matter power in {path}")
    k_hmpc, power_mpc_over_h_cubed = table[:, 0], table[:, 1]
    if (
        np.any(~np.isfinite(k_hmpc))
        or np.any(~np.isfinite(power_mpc_over_h_cubed))
        or np.any(k_hmpc <= 0.0)
        or np.any(power_mpc_over_h_cubed <= 0.0)
        or np.any(np.diff(k_hmpc) <= 0.0)
    ):
        raise RuntimeError(f"invalid k/P grid in {path}")
    # k is in h/Mpc, P in (Mpc/h)^3, and R=8 Mpc/h, so the h factors cancel.
    integrand = k_hmpc**3 * power_mpc_over_h_cubed * top_hat_window(8.0 * k_hmpc) ** 2 / (2.0 * math.pi**2)
    variance = float(simpson(integrand, x=np.log(k_hmpc)))
    if not math.isfinite(variance) or variance <= 0.0:
        raise RuntimeError(f"non-positive sigma8 variance from {path}")
    return math.sqrt(variance)


def load_rsd(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(f"RSD diagnostic data unavailable: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        required = {"name", "z", "fsigma8", "sigma", "omega_m_ref", "group", "source"}
        if reader.fieldnames is None or set(reader.fieldnames) != required:
            raise RuntimeError(f"unexpected RSD columns in {path}: {reader.fieldnames}")
        rows: list[dict[str, Any]] = []
        for raw in reader:
            row = {
                "name": raw["name"],
                "z": float(raw["z"]),
                "fsigma8": float(raw["fsigma8"]),
                "sigma": float(raw["sigma"]),
                "omega_m_ref": float(raw["omega_m_ref"]),
                "group": raw["group"],
                "source": raw["source"],
            }
            if not (row["z"] > 0.0 and row["sigma"] > 0.0):
                raise RuntimeError(f"invalid RSD record: {row}")
            rows.append(row)
    if not rows:
        raise RuntimeError("RSD diagnostic CSV contains no records")
    return rows


def solver_sigma8_values(solver_dir: Path) -> dict[float, float]:
    log = solver_dir / "solver.log"
    if not log.is_file():
        raise FileNotFoundError(f"solver log unavailable: {log}")
    values: dict[float, float] = {}
    for z_text, sigma_text in SIGMA8_PATTERN.findall(log.read_text(encoding="utf-8", errors="replace")):
        values[float(z_text)] = float(sigma_text)
    if not values:
        raise RuntimeError(f"no all-matter sigma8 values found in {log}")
    return values


def solver_velocity_growth_values(solver_dir: Path) -> dict[float, float]:
    log = solver_dir / "solver.log"
    if not log.is_file():
        raise FileNotFoundError(f"solver log unavailable: {log}")
    values: dict[float, float] = {}
    for z_text, growth_text in VELOCITY_GROWTH_PATTERN.findall(log.read_text(encoding="utf-8", errors="replace")):
        values[float(z_text)] = float(growth_text)
    if not values:
        raise RuntimeError(f"no velocity--density growth values found in {log}")
    return values


def sigma8_at(solver_dir: Path, redshift: float, cache: dict[float, float]) -> float:
    if redshift not in cache:
        cache[redshift] = sigma8_from_linear_power(matter_power_path(solver_dir, redshift))
    return cache[redshift]


def main() -> None:
    args = parse_args()
    if not math.isfinite(args.finite_difference_dz) or not 0.0 < args.finite_difference_dz <= 0.05:
        raise ValueError("finite-difference-dz must lie in (0, 0.05]")
    rows = load_rsd(args.rsd_data)
    if min(row["z"] for row in rows) <= args.finite_difference_dz:
        raise ValueError("finite-difference-dz must be below every data redshift")

    cache: dict[float, float] = {}
    predictions: list[dict[str, Any]] = []
    for row in rows:
        redshift = row["z"]
        z_low, z_high = redshift - args.finite_difference_dz, redshift + args.finite_difference_dz
        sigma_low = sigma8_at(args.solver_dir, z_low, cache)
        sigma_central = sigma8_at(args.solver_dir, redshift, cache)
        sigma_high = sigma8_at(args.solver_dir, z_high, cache)
        delta_ln_a = math.log1p(z_high) - math.log1p(z_low)
        fsigma8 = (sigma_low - sigma_high) / delta_ln_a
        residual = (fsigma8 - row["fsigma8"]) / row["sigma"]
        predictions.append(
            {
                **row,
                "sigma8_low_z": sigma_low,
                "sigma8": sigma_central,
                "sigma8_high_z": sigma_high,
                "f_sigma8_native": fsigma8,
                "residual_sigma": residual,
                "residual_square": residual * residual,
            }
        )

    diag = [row for row in predictions if row["group"] == "diag"]
    native_log_values = solver_sigma8_values(args.solver_dir)
    native_velocity_growth = solver_velocity_growth_values(args.solver_dir)
    sigma8_cross_check = []
    for redshift, printed_sigma8 in sorted(native_log_values.items()):
        path = matter_power_path(args.solver_dir, redshift)
        if path.is_file():
            integrated = sigma8_at(args.solver_dir, redshift, cache)
            sigma8_cross_check.append(
                {
                    "z": redshift,
                    "solver_printed_sigma8": printed_sigma8,
                    "power_integrated_sigma8": integrated,
                    "difference": integrated - printed_sigma8,
                }
            )

    velocity_growth_cross_check = []
    for prediction in predictions:
        redshift = prediction["z"]
        if redshift in native_velocity_growth:
            native_value = native_velocity_growth[redshift]
            prediction["solver_velocity_density_f_sigma8"] = native_value
            prediction["derivative_minus_velocity_density_f_sigma8"] = prediction["f_sigma8_native"] - native_value
            velocity_growth_cross_check.append(
                {
                    "z": redshift,
                    "power_derivative_f_sigma8": prediction["f_sigma8_native"],
                    "solver_velocity_density_f_sigma8": native_value,
                    "difference": prediction["f_sigma8_native"] - native_value,
                }
            )

    output = {
        "model": "R-Universe covariant KGB realized through native H-EFTCAMB RPH",
        "method": {
            "power_spectrum": "linear total-matter P(k,z) emitted by the executed H-EFTCAMB solver",
            "sigma8": "sqrt[integral d ln k k^3 P(k) W^2(8k)/(2 pi^2)]",
            "f_sigma8": "symmetric d sigma8/d ln a from spectra at z-dz and z+dz",
            "velocity_growth_cross_check": "H-EFTCAMB sigma8^2_vdelta/sigma8 output at each central redshift",
            "finite_difference_dz": args.finite_difference_dz,
        },
        "scope": (
            "Native linear-theory prediction and RSD residual audit. This is not an RSD likelihood and is not added to the "
            "Planck--Pantheon+--DESI--chronometer conditional statistic: survey window functions, fiducial-cosmology/AP "
            "transformations, nonlinear nuisance parameters, and covariances for the WiggleZ and SDSS-IV groups are absent."
        ),
        "data": {
            "file": args.rsd_data.name,
            "sha256": sha256(args.rsd_data),
            "record_count": len(rows),
            "diag_labelled_count": len(diag),
        },
        "solver": {
            "directory": str(args.solver_dir),
            "solver_log_sha256": sha256(args.solver_dir / "solver.log"),
            "sigma8_power_integral_cross_check": sigma8_cross_check,
            "f_sigma8_velocity_density_cross_check": velocity_growth_cross_check,
        },
        "diagnostic_only": {
            "diagonal_sum_of_squared_residuals_for_records_labelled_diag": sum(row["residual_square"] for row in diag),
            "not_a_likelihood": True,
        },
        "predictions": predictions,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2) + "\n", encoding="ascii")
    print(json.dumps(output, indent=2))
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
