#!/usr/bin/env python3
"""Regression test for the pinned GR CAMB reference calculation.

The numerical targets below are generated by CAMB 2.0.1 from the published
Planck reference inputs. This is an infrastructure test; it does not validate
the missing RFG-R extended-EFT backend.
"""

from __future__ import annotations

import math

from gr_reference_camb import calculate_reference


def _close(actual: float, expected: float, label: str) -> None:
    if not math.isclose(actual, expected, rel_tol=5.0e-6, abs_tol=1.0e-12):
        raise AssertionError(f"{label}: got {actual:.16e}, expected {expected:.16e}")


def main() -> None:
    result = calculate_reference()
    if result["camb_version"] != "2.0.1":
        raise AssertionError("the pinned CAMB version changed")
    _close(float(result["H0_check"]), 67.36, "H0")
    _close(float(result["sigma8"]), 8.110325278646e-1, "sigma8")
    cmb = result["cmb"]
    _close(float(cmb[2][0]), 1.0212264093554003e3, "D_2 TT")
    _close(float(cmb[200][0]), 5.602336966720086e3, "D_200 TT")
    _close(float(cmb[800][1]), 1.5583310963515325e1, "D_800 EE")
    _close(float(cmb[2000][2]), -1.8052915254769378e1, "D_2000 TE")
    lensing = result["lensing_pp"]
    _close(float(lensing[30]), 1.3854279943607025e-7, "lensing 30")
    matter = result["matter"]
    _close(float(matter[0.01]), 2.184522104962878e4, "P(0.01)")
    _close(float(matter[0.1999999999999999]), 1.9476469948181898e3, "P(0.2)")
    print("Pinned CAMB 2.0.1 GR reference regression passed")


if __name__ == "__main__":
    main()
