#!/usr/bin/env python3
"""Full multiplier-sector kinetic gate for locked R-Universe.

The integrated-by-parts multiplier action contains

    - Z(R)/2 (grad R)^2 - ell^2 grad(lambda).grad(R)

For homogeneous perturbations around any background, the Jordan-frame kinetic
Hessian in the field velocities (Rdot, lambdadot) is

    K = [[Z(R), ell^2],
         [ell^2, 0]]

up to the common positive volume factor a^3.  Its determinant is -ell^4.  The
non-minimal F(R)R term adds a positive Einstein-frame contribution to the RR
entry, but the determinant of [[Zeff, ell^2/F], [ell^2/F, 0]] remains negative
for finite ell and positive F.  This script evaluates both signatures on the
previously integrated locked background and records the conclusion.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
BACKGROUND = ROOT / "tables" / "locked_r_universe_background.csv"
RESULTS = ROOT / "code" / "full_lambda_stability_gate_results.json"
CSV = ROOT / "tables" / "full_lambda_stability_gate.csv"
FIG_PDF = ROOT / "figures" / "fig02_full_lambda_ghost_gate.pdf"
FIG_PNG = ROOT / "figures" / "fig02_full_lambda_ghost_gate.png"


def kinetic_eigenvalues(z_entry: np.ndarray, offdiag: np.ndarray | float) -> tuple[np.ndarray, np.ndarray]:
    root = np.sqrt(z_entry * z_entry + 4.0 * np.asarray(offdiag) ** 2)
    return 0.5 * (z_entry + root), 0.5 * (z_entry - root)


def main() -> None:
    df = pd.read_csv(BACKGROUND)
    # The current locked branch selected ell=0.7; the sign result is independent
    # of this value as long as ell is finite and nonzero.
    ell = 0.7
    z = df["Z"].to_numpy()
    f = df["F"].to_numpy()
    # Numerical derivative of F(R_c) for the Einstein-frame scalar contribution.
    rc = df["R_cal"].to_numpy()
    order = np.argsort(rc)
    dF_dR_sorted = np.gradient(f[order], rc[order], edge_order=1)
    dF_dR = np.empty_like(dF_dR_sorted)
    dF_dR[order] = dF_dR_sorted
    z_eff = z / f + 1.5 * (dF_dR / f) ** 2
    kp, km = kinetic_eigenvalues(z, ell**2)
    offdiag_einstein = ell**2 / f
    kp_e, km_e = kinetic_eigenvalues(z_eff, offdiag_einstein)
    out_df = pd.DataFrame(
        {
            "a": df["a"],
            "Z": z,
            "ell": ell,
            "K_plus": kp,
            "K_minus": km,
            "det_K": -ell**4,
            "F": f,
            "dF_dRc": dF_dR,
            "Z_eff_Einstein": z_eff,
            "K_plus_Einstein": kp_e,
            "K_minus_Einstein": km_e,
            "det_K_Einstein": -(offdiag_einstein**2),
        }
    )
    out_df.to_csv(CSV, index=False)

    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.plot(out_df["a"], out_df["K_plus"], label=r"$K_+$")
    ax.plot(out_df["a"], out_df["K_minus"], label=r"$K_-$")
    ax.plot(out_df["a"], out_df["K_minus_Einstein"], "--", label=r"$K_-^{E}$")
    ax.axhline(0.0, color="0.2", lw=0.9)
    ax.set_xscale("log")
    ax.set_xlabel("a")
    ax.set_ylabel("kinetic eigenvalue")
    ax.set_title("full multiplier kinetic gate")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_PDF)
    fig.savefig(FIG_PNG, dpi=180)
    plt.close(fig)

    result = {
        "gate": "full multiplier scalar kinetic Hessian",
        "kinetic_matrix": "[[Z(R), ell^2], [ell^2, 0]]",
        "determinant": "-ell^4",
        "einstein_frame_matrix": "[[Z/F + 3/2 (F_R/F)^2, ell^2/F], [ell^2/F, 0]]",
        "einstein_frame_determinant": "-ell^4/F^2",
        "background_independent_conclusion": (
            "For any finite nonzero ell and positive Z in the Jordan-frame "
            "homogeneous Hessian, det(K)<0. Including the positive kinetic "
            "contribution generated by the non-minimal F(R)R term changes the "
            "RR entry but leaves det(K_E)=-ell^4/F^2<0 for F>0. The hard "
            "multiplier localization therefore has an indefinite scalar "
            "kinetic signature before data fitting. A full ADM reduction is "
            "still the required final proof for the metric-scalar system."
        ),
        "current_branch": {
            "ell": ell,
            "min_Z": float(np.min(z)),
            "min_F": float(np.min(f)),
            "min_Z_eff_Einstein": float(np.min(z_eff)),
            "min_K_plus": float(np.min(kp)),
            "max_K_minus": float(np.max(km)),
            "min_K_minus": float(np.min(km)),
            "min_K_plus_Einstein": float(np.min(kp_e)),
            "max_K_minus_Einstein": float(np.max(km_e)),
            "min_K_minus_Einstein": float(np.min(km_e)),
            "all_K_plus_positive": bool(np.all(kp > 0)),
            "all_K_minus_negative": bool(np.all(km < 0)),
            "all_K_plus_Einstein_positive": bool(np.all(kp_e > 0)),
            "all_K_minus_Einstein_negative": bool(np.all(km_e < 0)),
        },
        "verdict": "FAIL: locked Lagrange-multiplier finite-window action is not viable without a degeneracy or replacement of the multiplier sector",
        "possible_next_theory_move": (
            "Replace the hard multiplier by a healthy auxiliary field or a "
            "degenerate constrained construction whose kinetic matrix has no "
            "negative propagating eigenvalue."
        ),
        "outputs": {
            "csv": str(CSV.relative_to(ROOT)),
            "figure": str(FIG_PDF.relative_to(ROOT)),
        },
    }
    RESULTS.write_text(json.dumps(result, indent=2))
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
